enabled: true

drop:
  # When a player kills an entity should the head be dropped?
  entity: true
  # When a player kills a player should the head be dropped?
  player: true
  # Should the /Skull command be enabled?
  command: true