enabled: true

drop:
  # When an entity is killed by a player should the head be dropped?
  entity: true
  # When a player is killed by a player should the head be dropped?
  player: true
  # Should the /Skull command be enabled?
  command: true