name: Skulls
load: POSTWORLD
version: 0.1
author: ByAlexius
main: net.byalexius.skulls.Skulls
api-version: 1.20

commands:
  skull:
    description: Get the head of the specified Player
    permission: skulls.skull